### ISSUE TITLE
Tag cutter versions in this repo too

### ISSUE THREAD

**Issue by ismaell** [rizinorg/cutter-translations#2]
Provide tags matching the cutter repo.

The idea is that since git-archive and github archives aren't recursive (i.e. don't archive submodules), you can generate matching archives for the repositories via the tag.

E.g.:
```
GIT_DIR=cutter/.git git archive v1.11.0 --prefix=cutter-1.11.0/
GIT_DIR=cutter-translations/.git git archive v1.11.0 --prefix=cutter-1.11.0/src/translations/
```
And then combine those. The same applies to github URLs.

**Comment by ismaell** [comment]
I guess it's not relevant anymore...

**Comment by xarkes** [comment]
Hello, I think it's still relevant, we can start adding a tag on this repo too for next version.

**Comment by thestr4ng3r** [comment]
Cutter now provides a proper source tarball, which contains the translations and should be used instead of the git-archive one: https://github.com/rizinorg/cutter/releases/download/v2.1.2/Cutter-v2.1.2-src.tar.gz
